export const GET_USER = 'GET_USER'
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA'
export const CHANGE_USER_DATA = 'CHANGE_USER_DATA'

export const GET_NETWORKS = 'GET_NETWORKS'
export const GET_NETWORK_STATISTIC = 'GET_NETWORK_STATISTIC'
export const GET_NETWORK_HISTORY = 'GET_NETWORK_HISTORY'

export const SAVE_NETWORK = 'SAVE_NETWORK'
export const EDIT_NETWORK = 'EDIT_NETWORK'
export const DELETE_NETWORK = 'DELETE_NETWORK'

export const WS_EDIT_NODE = 'WS_EDIT_NODE'
export const EDIT_NODE = 'EDIT_NODE'
export const ADD_NODE = 'ADD_NODE'
export const DELETE_NODE = 'DELETE_NODE'
export const SAVE_PREV_NETWORK = 'SAVE_PREV_NETWORK'

export const CLEAR_NETWORK_DATA = 'CLEAR_NETWORK_DATA'

export const DELETE_USER = 'DELETE_USER'
export const EDIT_TEAM_USER = 'EDIT_TEAM_USER'

export const LOADING_REQUEST = 'LOADING_REQUEST'
export const SET_LOADING_PROGRESS = 'SET_LOADING_PROGRESS'

export const GET_ALERTS = 'GET_ALERTS'
export const CLEAR_ALERTS = 'CLEAR_ALERTS'

export const GET_SHARED_USERS = 'GET_SHARED_USERS'
export const CLEAR_SHARED_USERS = 'CLEAR_SHARED_USERS'

export const NETWORK_SHARED = 'NETWORK_SHARED'
export const NETWORK_UNSHARED = 'NETWORK_UNSHARED'
export const NETWORK_EDITED = 'NETWORK_EDITED'

export const GET_CAPTIVE_PORTALS = 'GET_CAPTIVE_PORTALS'

export const SELECT_TIME_RANGE = 'SELECT_TIME_RANGE'

export const SET_THEME_MODE = 'SET_THEME_MODE'
