export const BLE_INIT = 'BLE_INIT'

export const BLE_SEARCH_START = 'BLE_SEARCH_START'
export const BLE_SEARCH_STOP = 'BLE_SEARCH_STOP'
export const BLE_SEARCH_ERROR = 'BLE_SEARCH_ERROR'

export const BLE_DEVICE_DISCOVERED = 'BLE_DEVICE_DISCOVERED'
export const BLE_DEVICE_CONNECTING = 'BLE_DEVICE_CONNECTING'
export const BLE_DEVICE_CONNECTED = 'BLE_DEVICE_CONNECTED'
export const BLE_DEVICE_CONNECT_TIMEOUT = 'BLE_DEVICE_CONNECT_TIMEOUT'
export const BLE_DEVICE_DISCONNECTED = 'BLE_DEVICE_DISCONNECTED'
export const BLE_DEVICE_READY_TO_EDIT = 'BLE_DEVICE_READY_TO_EDIT'

export const BLE_CHARACTERISTICS_DISCOVERED = 'BLE_CHARACTERISTICS_DISCOVERED'
export const BLE_UART_SUBSCRIBED = 'BLE_UART_SUBSCRIBED'
export const BLE_UART_UNSUBSCRIBED = 'BLE_UART_UNSUBSCRIBED'

export const BLE_LOAD_ENABLED = 'BLE_LOAD_ENABLED'
export const BLE_DORMANT_ENABLED = 'BLE_DORMANT_ENABLED'
export const BLE_SYSTEM_RESET = 'BLE_SYSTEM_RESET'
export const BLE_BATTERY_UPDATE = 'BLE_BATTERY_UPDATE'

export const SET_LOADING_PROGRESS = 'SET_LOADING_PROGRESS'

export const IN_BLE_SEARCH_SCREEN = 'IN_BLE_SEARCH_SCREEN'

export const OUT_BLE_SEARCH_SCREEN = 'OUT_BLE_SEARCH_SCREEN'

export const GET_ACCESS_POINTS = 'GET_ACCESS_POINTS'
