export const DFU_SUBSCRIBE = "DFU_SUBSCRIBE"
export const DFU_UNSUBSCRIBE = "DFU_UNSUBSCRIBE"
export const CHECK_FIRMWARE = "CHECK_FIRMWARE"
export const CHECK_FIRMWARE_FINISHED = "CHECK_FIRMWARE_FINISHED"
export const CHECK_FIRMWARE_SUCCESS = "CHECK_FIRMWARE_SUCCESS"
export const CHECK_FIRMWARE_FAIL = "CHECK_FIRMWARE_FAIL"

export const SELECT_BATTERY_0V4 = "SELECT_BATTERY_0V4"

export const DOWNLOAD_FIRMWARE = 'DOWNLOAD_FIRMWARE'
export const DOWNLOAD_FIRMWARE_SUCCESS = 'DOWNLOAD_FIRMWARE_SUCCESS'
export const DOWNLOAD_FIRMWARE_FAIL = 'DOWNLOAD_FIRMWARE_FAIL'
export const DOWNLOAD_PERCENT = 'DOWNLOAD_PERCENT'

export const DFU_INIT = "DFU_INIT"
export const DFU_UPDATING = "DFU_UPDATING"
export const DFU_UPDATED = "DFU_UPDATED"
export const DFU_ERROR = "DFU_ERROR"
export const DFU_PERCENT = "DFU_PERCENT"

export const APPLY_UPDATE = "APPLY_UPDATE"
