# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# before_all do
#  ensure_git_branch
#  ensure_git_status_clean
#  git_pull
# end

default_platform(:ios)

# match(type: "development")

platform :android do
  desc 'Build the Android application.'
    private_lane :build do
      gradle(task: 'clean', project_dir: '../../android/')
      gradle(task: 'assemble', build_type: 'Release', project_dir: '../../android/')
    end
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  desc "This will also make sure the profile is up to date"  
  lane :beta do
    # UI.important "Important Message"
    # UI.error "O NO!"
    # UI.message "Basic blah"
    answer = UI.select("Would you like to add a Changelog?", ["Yes", "No"])
    changelog = ask('Type Changelog message:') if answer == "Yes"
    
    # Get latest certs appstore
    # match(type: 'appstore')
    
    increment_build_number(xcodeproj: "mesh.xcodeproj")
    build_app(scheme: "mesh")
    
    #if changelog
    #  upload_to_testflight(changelog: changelog)
    #else
    #  upload_to_testflight
    #end    
    
  end

  lane :version do
    # increment_version_number(xcodeproj: "mesh.xcodeproj", bump_type: "patch")
    increment_build_number(xcodeproj: "mesh.xcodeproj")
    # fastlane run increment_version_number bump_type:"patch"
  end

  desc "Build application"
  lane :bu do
    gym(
      scheme: "mesh",
      clean: true,
      output_directory: "build",
      export_options: {
        method: "development"
      }
    )
  end

end